Repository covid19india/covid19india-react, pull requests merged in 2020-03, with the labels that each got.

#16 Fixed timeseries graph to show correct values.
  src/components/timeseries.js
Labels: bug

#17 Timeseries position
  src/components/choropleth.js
  src/components/timeseries.js
Labels: enhancement

#20 Fixed active deltas in level.
  src/components/choropleth.js
  src/components/level.js
  src/components/table.js
Labels: bug, enhancement

#45 Active delta
  package-lock.json
  package.json
  src/App.scss
  src/components/choropleth.js
  src/components/home.js
  src/components/minigraph.js
  src/components/timeseries.js
Labels: enhancement

#43 Outline state boundary on hover instead of filling colour
  src/components/choropleth.js
Labels: enhancement

#97 Added state wise deltas
  src/App.scss
  src/components/row.js
  src/components/table.js
Labels: enhancement

#85 fix typo of FAQ in navbar and link.
  src/App.js
  src/components/navbar.js
Labels: enhancement

#113 Use cursor to slide across charts
  src/components/timeseries.js
Labels: enhancement

#131 Fix sorting when values are equal
  src/components/table.js
Labels: bug

#144 Revert to right alignment for numbers in table
  src/App.scss
  src/components/row.js
Labels: enhancement

#164 Added support for districts in table.
  src/App.scss
  src/components/row.js
  src/components/table.js
Labels: enhancement

#88 District level graph exploration
  public/andamannicobarislands.json
  public/arunachalpradesh.json
  public/assam.json
  public/bihar.json
  public/chhattisgarh.json
  public/delhi.json
  public/goa.json
  public/gujarat.json
  public/haryana.json
  public/himachalpradesh.json
  public/jharkhand.json
  public/karnataka.json
  public/kerala.json
  public/madhyapradesh.json
  public/maharashtra.json
  public/manipur.json
  public/meghalaya.json
  public/mizoram.json
  public/nagaland.json
  public/odisha.json
  public/punjab.json
  public/rajasthan.json
  public/sikkim.json
  public/tamil-nadu.json
  public/tripura.json
  public/uttarakhand.json
  public/uttarpradesh.json
  public/westbengal.json
  src/App.scss
  src/components/choropleth.js
  src/components/home.js
  src/components/mapexplorer.js
  src/constants.js
Labels: Priority: Critical, Status: In Progress, Type: Enhancement

#257 Update Bangalore to Bengaluru
  public/maps/karnataka.json
Labels: Type: Bug

#206 Added arrow icon to indicate the current sort order
  src/App.scss
  src/components/table.js
Labels: Type: Enhancement

#266 #259: Added Alt tags for SEO Enchancment
  src/App.js
  src/components/navbar.js
  src/components/summary.js
Labels: Status: In Progress

#302 Fix: Uttarakhand Map does not show information for Pauri district #301
  public/maps/uttarakhand.json
Labels: Status: On Hold

#320 Update Rajasthan District Names
  public/maps/rajasthan.json
Labels: Status: Blocked

#297 District hover in the table changes the map and map stats
  public/maps/rajasthan.json
  public/maps/uttarakhand.json
  src/components/choropleth.js
  src/components/home.js
  src/components/mapexplorer.js
  src/components/row.js
  src/components/table.js
Labels: Status: In Progress

#328 Fix react-hook related warnings
  .eslintrc.js
  src/components/banner.js
  src/components/choropleth.js
  src/components/level.js
  src/components/mapexplorer.js
  src/components/minigraph.js
  src/components/row.js
  src/components/table.js
  src/components/timeseries.js
Labels: Priority: High, Status: In Progress

#386 Fix states with zero cases not showing as white
  src/components/choropleth.js
Labels: Type: Bug

#382 Streamline map highlighting method
  src/components/choropleth.js
  src/components/home.js
  src/components/mapexplorer.js
Labels: Type: Bug

#339 Added support for patients db.
  .eslintrc.js
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/components/downloadblock.js
  src/components/patientdb.js
  src/components/patients.js
Labels: Priority: High, Status: In Progress

#429 Map Data Cleanup
  public/maps/delhi.json
  public/maps/gujarat.json
  public/maps/india.json
  public/maps/karnataka.json
  public/maps/maharashtra.json
  public/maps/sikkim.json
  public/maps/telugana.json
  public/maps/uttarpradesh.json
  src/components/choropleth.js
Labels: Geography

#357 Feature: Localization support
  .vscode/settings.json
  CONTRIBUTING.md
  package-lock.json
  package.json
  public/locales/bn.json
  public/locales/en.json
  public/locales/gu.json
  public/locales/hi.json
  public/locales/kn.json
  public/locales/mr.json
  public/locales/or.json
  public/locales/pa.json
  public/locales/ta.json
  public/locales/te.json
  public/locales/ur.json
  src/App.js
  src/App.scss
  src/components/choropleth.js
  src/components/home.js
  src/components/languageswitcher.js
  src/components/level.js
  src/components/links.js
  src/components/mapexplorer.js
  src/components/navbar.js
  src/components/row.js
  src/components/summary.js
  src/components/table.js
  src/components/timeseries.js
  src/constants.js
  src/i18n/index.js
  src/i18n/locales.json
  src/index.js
Labels: Priority: High, Status: In Progress
