Repository covid19india/covid19india-react, pull requests merged in 2020-04, with the labels that each got.

#363 feature #136 : Log scale switch for cumulative charts
  src/App.scss
  src/components/home.js
  src/components/timeseries.js
Labels: Status: In Progress

#465 Reduce map data in andamannicobarislands.json
  public/maps/andamannicobarislands.json
Labels: Geography

#593 Fix: Implement sanity check
  package-lock.json
  src/components/home.js
  src/components/timeseries.js
  src/utils/common-functions.js
Labels: Status: Completed

#470 Fix - 472 / Map for ramanathapuram - TamilNadu
  public/maps/tamil-nadu.json
Labels: Geography, Status: In Progress

#661 Enhancements for DB
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/components/banner.js
  src/components/choropleth.js
  src/components/home.js
  src/components/level.js
  src/components/mapexplorer.js
  src/components/minigraph.js
  src/components/patientdb.js
  src/components/patients.js
  src/components/table.js
Labels: Status: In Progress

#539 Deep Dive Tab
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/components/Charts/agechart.js
  src/components/Charts/allstates.js
  src/components/Charts/dailyconfirmedchart.js
  src/components/Charts/genderchart.js
  src/components/Charts/nationalitychart.js
  src/components/Charts/statechart.js
  src/components/Charts/totalconfirmedchart.js
  src/components/deepdive.js
  src/utils/common-functions.js
Labels: Type: Enhancement

#733 Add transition animations to charts
  src/components/timeseries.js
  src/utils/common-functions.js
Labels: Status: Review Needed

#891 Disable button
  src/components/resources.js
Labels: Status: Completed

#981 Feature/essentials
  package-lock.json
  package.json
  public/index.html
  src/App.scss
  src/components/resources.js
  src/components/resourcetable.js
Labels: Essentials

#1166 Fix for test cases failing because of 00584fa
  src/__tests__/components/Level.test.js
Labels: Test

#877 Fix: Matched style of select in demographics to that of homepage
  src/App.scss
Labels: Type: Enhancement

#1042 #355 Added test for Row component
  package-lock.json
  package.json
  src/__tests__/components/Row.test.js
  src/setupTests.js
Labels: Test

#1220 Date problem in notification fixed.
  src/components/updates.js
Labels: Status: In Progress

#1237 Notification bell icon dot.
  src/components/home.js
  src/components/updates.js
Labels: Status: Revision Needed

#1183 Search bar essentials
  src/App.scss
  src/components/Essentials/essentialsaccordionmobile.js
  src/components/Essentials/essentialsfiltersdesktop.js
  src/components/Essentials/essentialsfiltersmobile.js
  src/components/Essentials/essentialsutls.js
  src/components/resources.js
  src/components/resourcetable.js
Labels: Essentials

#1304 Category sorting and Google Tag tracker
  public/index.html
  src/components/Essentials/essentialstabledesktop.js
  src/components/resources.js
Labels: Essentials

#1082 Style: Improve upon UI/UX of DeepDive
  package-lock.json
  package.json
  src/App.scss
  src/components/Charts/agechart.js
  src/components/Charts/allstates.js
  src/components/Charts/chart-defaults.js
  src/components/Charts/dailyconfirmedchart.js
  src/components/Charts/genderchart.js
  src/components/Charts/nationalitychart.js
  src/components/Charts/totalconfirmedchart.js
  src/components/deepdive.js
Labels: Deep-Dive

#1016 Feat: State wise growth trend, new cases vs confirmed cases
  src/components/Charts/growthtrendchart.js
  src/components/deepdive.js
Labels: Status: In Progress

#1057 Fix: Show the confirmed cases in DeepDive dailys.
  src/components/Charts/dailyconfirmedchart.js
Labels: Deep-Dive

#1423 Style: Expand charts to fit container in DeepDive.
  src/App.scss
Labels: Deep-Dive

#1424 Improv: Add legends for daily confirmed chart in DeepDive
  src/components/Charts/dailyconfirmedchart.js
Labels: Deep-Dive

#1568 Feat: code reduction using timeseriesexplorer.
  src/components/home.js
  src/components/state.js
  src/components/timeseries.js
  src/components/timeseriesexplorer.js
Labels: Status: Completed

#1554 Search using keywords
  src/components/resources.js
  src/components/resourcetable.js
Labels: Essentials
